### ISSUE TITLE
wrong-type-argument symbolp "user"

### ISSUE THREAD

**Issue by chrchr** [douo/magit-gptcommit#2]
Perhaps I have an incompatible gptel version? Mine says ;; Version: 0.8.5

```
Debugger entered--Lisp error: (wrong-type-argument symbolp "user")
  gptel-curl--get-args(((:role "user" :content "You are an expert programmer writing a commit mess...")) "686ec06b06e150146ca91de33f44f809")
  magit-gptcommit-gptel-get-response("..." (:prompt ((:role "user" :content "You are an expert programmer writing a commit mess...")) :buffer #<buffer magit: .emacs.d> :position #<marker at 338 in magit: .emacs.d>) magit-gptcommit--stream-insert-response)
  magit-gptcommit--insert(staged)
  magit-gptcommit--status-insert-gptcommit()
```

**Comment by LemonBreezes** [comment]
> Perhaps I have an incompatible gptel version? Mine says ;; Version: 0.8.5
> 
> ```
> Debugger entered--Lisp error: (wrong-type-argument symbolp "user")
>   gptel-curl--get-args(((:role "user" :content "You are an expert programmer writing a commit mess...")) "686ec06b06e150146ca91de33f44f809")
>   magit-gptcommit-gptel-get-response("..." (:prompt ((:role "user" :content "You are an expert programmer writing a commit mess...")) :buffer #<buffer magit: .emacs.d> :position #<marker at 338 in magit: .emacs.d>) magit-gptcommit--stream-insert-response)
>   magit-gptcommit--insert(staged)
>   magit-gptcommit--status-insert-gptcommit()
> ```

Same. I am also getting this error and cannot use this package because of it.

**Comment by douo** [comment]
Can you provide your gptel version？Let me try to see if I can reproduce it.

**Comment by LemonBreezes** [comment]
> Can you provide your gptel version？Let me try to see if I can reproduce it.

Sure. I'm on the latest commit, 70889ad * master origin/master gptel-gemini: Add Gemini 1.5 (#284).

**Comment by avishefi** [comment]
There was support for native json added to `gptel` and the format of queries has changed and can possibly be different between LLMs.

I've fixed this locally on `magit-gptcommit--insert` by replacing:

```emacs-lisp
(magit-gptcommit-gptel-get-response
 key
 (list :prompt (list (list :role "user" :content (format magit-gptcommit-prompt diff)))
       :buffer buf
       :position (point-marker))
 #'magit-gptcommit--stream-insert-response)
```

with:

```emacs-lisp

(magit-gptcommit-gptel-get-response
 key
 (list :prompt `(:contents [(:role "user" :parts (:text ,(format magit-gptcommit-prompt diff)))])
       :buffer buf
       :position (point-marker))
 #'magit-gptcommit--stream-insert-response)
```


I think a better way would be to call `gptel-request` instead of calling internal functions, this way support for the prompt structure for each backend is maintained by `gptel`.

**Comment by avishefi** [comment]
@douo see PR #4

**Comment by avishefi** [comment]
The project moved to llm so this should be irrelevant now.
